import argparse
import json
import os
import sys
from datetime import datetime

import ollama


# Prompt builder

SYSTEM_PROMPT = """You are an expert in bioinformatics, sequencing technologies, genomics data analysis, and adjacent fields.

You are given findings from a MultiQC report, generated by a bioinformatics workflow.
MultiQC supports various bioinformatics tools that output QC metrics, and aggregates those metrics
into a single report. It outputs a "General Statistics" table with key metrics for each sample across
all tools. That table is followed by more detailed sections from specific tools, that can include tables,
as well as plots of different types (bar plot, line plot, scatter plot, heatmap, etc.)

You are given data of a MultiQC report. Your task is to analyse the data and give a concise summary.


----------------------

Tools used in the report:

1. Sample Sheet
Description: The sample sheet provided as input to the pipeline

2. Atlas Summary
Description: Summary of the cells and genes in the atlas. If same atlas is used for multiple samples, table rows will be repeated

3. Atlas Cell Types
Description: Summary of the cell types in the atlas

4. Input Summary
Description: Summary of the AnnData object right after it was read

5. Output Cell Types
Description: Assigned cell types based on deconvolution / cell typing results

6. Cell Type Probabilities
Description: Average max cell type probabilities used to assign the cell types (greater is better)

7. Squidpy Ligrec Interactions
Description: Mean interaction across samples shown as no differential interactions were found between ['sample2'] and ['sample1']

8. Moran I Interactions
Description: Mean interaction across samples shown as no differential interactions were found between ['sample2'] and ['sample1']

9. Spatial Neighbors
Description: Cell type immediate neighborhood across samples"""


def build_prompt(report: dict) -> str:
    report_str = json.dumps(report, indent=2)
    return (
        "Here is the annotated MultiQC spatial transcriptomics report.\n"
        "Please analyze it and provide a structured biological interpretation.\n\n"
        f"```json\n{report_str}\n```"
    )

# Ollama call

def call_ollama(prompt: str, model: str, system: str = SYSTEM_PROMPT) -> str:
    """Send prompt to Ollama and return the response text."""
    print(f"[interpret] Calling model '{model}' via Ollama...")

    response = ollama.chat(
        model=model,
        messages=[
            {"role": "system", "content": system},
            {"role": "user",   "content": prompt},
        ],
        options={"num_ctx": 32768},
    )

    return response["message"]["content"]


def load_report(path: str) -> dict:
    if not os.path.exists(path):
        sys.exit(f"[error] Input file not found: {path}")
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def save_output(text: str, path: str) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"[interpret] Response saved to: {path}")


# Entry point

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Pass an annotated MultiQC JSON report to a local Ollama model."
    )
    parser.add_argument(
        "--input", "-i",
        required=True,
        help="Path to the annotated JSON report (output of main.py)",
    )
    parser.add_argument(
        "--model", "-m",
        default="gemma4",
        help="Ollama model name to use (default: llama3)",
    )
    parser.add_argument(
        "--output", "-o",
        default=None,
        help="Path to save the LLM response. Defaults to <input_stem>_interpretation.txt",
    )
    parser.add_argument(
    "--num_ctx",
    type=int,
    default=32768,
    help="Context window size (default: 32768)",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    if args.output is None:
        stem = os.path.splitext(os.path.basename(args.input))[0]
        out_dir = os.path.dirname(os.path.abspath(args.input))
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        args.output = os.path.join(out_dir, f"{stem}_interpretation_{timestamp}.txt")

    print(f"[interpret] Loading report: {args.input}")
    report = load_report(args.input)

    section_count = sum(1 for v in report.values() if isinstance(v, dict) and "data" in v)
    print(f"[interpret] Loaded {section_count} data sections.")

    prompt = build_prompt(report)
    response_text = call_ollama(prompt, model=args.model)

    save_output(response_text, args.output)

    print("LLM RESPONSE PREVIEW (first 1000 chars)")
    print(response_text[:1000])
    if len(response_text) > 1000:
        print(f"\n... [{len(response_text) - 1000} more characters in saved file]")


if __name__ == "__main__":
    main()